server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online-banking?verifyServerCertificate=false&useSSL=true
    username: root
    password: root
# Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update